### PR TITLE
Fix some issues with the Ode library and update installation instructions

### PR DESCRIPTION
**Pull request by munshkr**
@pabloriera could you test this branch? I haven't been able to make it work on my machine (neither master nor this branch), I have no sound. Not sure if this is broken, or if it's something else.

My specs are:
* Python 3.6
* Supercollider 3.9.3

### CODE REVIEW

**Comment by pabloriera** [comment]
The merge went smooth. I have sound and all the changes are perfect. The only difference is that I am using Python 3.5.2 and Supercollider 3.8.0. I will try the system in your configuration to see if that is the reason.

**Comment by pabloriera** [comment]
Also I run scide to test it, not sclang. Could that make a difference?

**Comment by pabloriera** [comment]
Is scsynth running?

**Comment by munshkr** [comment]
I think Oderk4 can't open the .so files, I'm getting a `lib.so not open` message on sclang. Let me check if it's a path problem.

**Pull request merged**
